version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - bot-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: discord_bot
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: discord_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - bot-network

volumes:
  postgres-data:

networks:
  bot-network:
    driver: bridge