# Configuration Nixpacks optimisée pour Railway 2025
[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --production --silent --no-progress --no-fund --no-audit"]

[start]
cmd = "node index.js"

[phases.build]
allowDirty = true
