[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build || true"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
