# Configuration Nixpacks pour bot Discord Node.js
# Configuration professionnelle pour production Railway

# Spécifier les providers
[phases.setup]
pkgsPath = "nixpkgs.json"
nixPkgs = ["nodejs_18", "npm-9_x"]

# Phase d'installation des dépendances
[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm --version",
    "node --version",
    "npm ci --only=production --no-audit --no-fund"
]

# Phase de build (si nécessaire)
[phases.build]
dependsOn = ["install"]
cmds = [
    "echo 'Build terminé'"
]

# Configuration du démarrage
[start]
cmd = "cd BOT-PRET-main && node --optimize-for-size --max-old-space-size=512 src/index.js"