[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
dependsOn = ['setup']
cmds = [
    'rm -rf node_modules package-lock.json',
    'npm install --save-exact --legacy-peer-deps',
    'npm audit fix --force || true'
]

[start]
cmd = 'node BOT-PRET-main/src/index.js'
