[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "npm --version",
    "node --version",
    "npm install --omit=dev --no-audit --no-fund"
]

[phases.build]
# Désactiver complètement la phase de build pour éviter le conflit npm ci
cmds = []

[start]
cmd = "node BOT-PRET-main/src/index.js"