[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "npm --version",
    "node --version",
    "npm install --omit=dev --no-audit --no-fund"
]

[start]
# Override le custom start command de Railway
cmd = "node BOT-PRET-main/src/index.js"