[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[start]
cmd = "node start.mjs"

[variables]
NODE_ENV = "production"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
