[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "npm --version",
    "node --version",
    "npm install --production --no-audit --no-fund"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node BOT-PRET-main/src/index.js"