[phases.setup]
pkgs = ["nodejs_21"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install --production --silent --no-progress --no-fund --no-audit"]

[phases.build]
dependsOn = ["install"]
allowDirty = true

[start]
cmd = "node index.js"
dependsOn = ["build"]

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=512"
