[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "wget"]

[phases.install]
cmds = [
    "npm ci --no-audit --no-fund --production=false"
]

[phases.build]
cmds = [
    "npm run build",
    "npm prune --production",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=512"
